blog/urls.py
from django.urls import path
from blog.views import (
    ArticleListView,
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    CategoryListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
)


app_name = 'blog'


urlpatterns = [
    # Articles
    path('', ArticleListView.as_view(), name='all_articles'),
    path('new', ArticleCreateView.as_view(), name='new_article'),
    path('<int:pk>', ArticleDetailView.as_view(), name='article'),
    path('<int:pk>/update', ArticleUpdateView.as_view(), name='update_article'),
    # Categories
    path('categories', CategoryListView.as_view(), name='all_categories'),
    path('categories/new', CategoryCreateView.as_view(), name='new_category'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category'),
    path('categories/<int:pk>/update', CategoryUpdateView.as_view(), name='update_category'),
    path('categories/<int:pk>/delete', CategoryDeleteView.as_view(), name='delete_category'),
]   

cauf_blog_2/urls.py
from django.contrib import admin
from django.urls import path, include
from cauf_blog_2.views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from pytz import timezone
from markdown import markdown, Markdown
from cauf_blog_2.settings import (
    MARKDOWN_EXTENSIONS, 
    MARKDOWN_EXTENSIONS_CONFIG,
    TIME_ZONE,
)


class Category(models.Model):
    caption = models.CharField('название', max_length=50)
    description = models.TextField('описание', blank=True, default='')
    parent = models.ForeignKey(
        'self', 
        on_delete=models.CASCADE,
        related_name='childs', 
        verbose_name='родитель',
        blank=True, 
        null=True,
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __repr__(self):
        return f'<Category {self.id}:"{self.caption}">'

    def __str__(self):
        return self.caption


class NormalTag(models.Model):
    text = models.CharField('текст', max_length=255)

    class Meta:
        verbose_name = 'нормализованный тег'
        verbose_name_plural = 'нормализованные теги'

    def __repr__(self):
        return f'<NormalTag {self.id}:"{self.text}">'

    def __str__(self):
        return self.text


class Tag(models.Model):
    text = models.CharField('текст', max_length=255)
    normal_tag = models.ForeignKey(
        NormalTag, 
        on_delete=models.CASCADE, 
        related_name='tags',
        verbose_name='нормализованный тег',
    )

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'

    def __repr__(self):
        return f'<Tag {self.id}:"{self.text}">'

    def __str__(self):
        return self.text


class Article(models.Model):
    caption = models.CharField('название', max_length=255)
    preview = models.TextField('разметка описания', blank=True, default='')
    text = models.TextField('разметка текста')
    edit_dt = models.DateTimeField('дата правки', blank=True, null=True)
    shows_count = models.IntegerField(
        'количество показов', 
        blank=True, 
        default=0, 
    )
    create_dt = models.DateTimeField('дата создания', auto_now=True)
    public_dt = models.DateTimeField('дата публикации', default=datetime.now())
    tags = models.ManyToManyField(
        Tag,
        related_name='articles',
        verbose_name='теги',
        blank=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='articles',
        verbose_name='категория',
    )

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'

    def __repr__(self):
        print_caption = (
            f'{self.caption[:20]}...'
            if len(self.caption) > 20
            else self.caption
        )
        return f'<Article {self.id}:{print_caption!r}>'

    def __str__(self):
        return self.caption

    def save(self, *args, **kwargs):
        tz = timezone(TIME_ZONE)
        self.edit_dt = datetime.now(tz=tz)
        super(Article, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'pk':self.pk})

blog/forms.py
from django.forms import (
    ModelForm, 
    CharField, 
    Form,
    ImageField,
)
from django.forms.widgets import TextInput
from blog.models import (
    Article,
    Category,
)


class ArticleForm(ModelForm):
    tags = CharField(max_length=255, label="Теги")
    class Meta:
        model = Article
        fields = [
            'caption', 
            'preview', 
            'text', 
            'public_dt', 
            'tags',
            'category',
        ]
        localized_fields = '__all__'


class ImageForm(Form):
    image_file = ImageField(
        allow_empty_file=False, 
        required=True,
    )


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = (
            'caption',
            'description',
            'parent',
        )
        localized_fields = '__all__'

blog/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from blog.models import (
    Article,
    Category,
)
from blog.forms import (
    ArticleForm,
    CategoryForm,
)


def home(request):
    return redirect('blog:all_articles')


class ArticleListView(ListView):
    template_name = 'all_articles.html'
    model = Article


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article.html'


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article_update.html'
    # login_url = reverse('login')


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article_update.html'


class CategoryListView(ListView):
    template_name = 'all_categories.html'
    model = Category


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category.html'


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category_update.html'
    
    def get_success_url(self):
        return reverse('blog:category', args=(self.object.pk,))


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category_update.html'

    def get_success_url(self):
        return reverse('blog:category', args=(self.object.pk,))


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category

    def get_success_url(self):
        return reverse('blog:all_categories')

cauf_blog_2/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            nxt = request.POST.get('next')
            if nxt:
                return redirect(nxt)
            return redirect('blog:all_articles')
        return render(request, 'login.html', {
            'error': 'Неправильный логин или пароль',
        })
    return render(request, 'login.html')


def logout_view(request):
    logout(request)
    return redirect('blog:all_articles')

blog/templates/all_articles.html
{% extends "base.html" %}
{% load markdown_extras %}

{% block title %}Все статьи{% endblock title %}

{% block content %}
<h1>Статьи</h1>
{% if user.is_authenticated %}
<div class="toolbar">
    <a class="button" href="{% url 'blog:new_article' %}"><i class="fa fa-plus fa-lg" aria-hidden="true"></i></a>
</div>
{% endif %}
{% if object_list.count > 0 %}
    {% for article in object_list %}
    <div>
        <article class="blog-post-card">
            <h2>{{ article.caption }}</h2>
            <p class="preview">{{ article.preview | markdown | safe }}</p>
            <p class="article-bar">
                <a href="{% url 'blog:article' article.pk %}"><i class="fa fa-newspaper-o" aria-hidden="true"></i> Читать</a>
                &#124;
                Категория: <a href="{% url 'blog:category' article.category.pk %}">{{article.category.caption}}</a>
                &#124;
                Дата публикации: {{article.public_dt|date:"l d F Y"}} г.
                {% if user.is_authenticated %}
                &#124;
                <a href="" class="button small"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <a href="" class="button small"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                {% endif %}
            </p>
        </article>
    </div>
    {% endfor %}
{% else %}
<p>В даном разделе нет статей</p>
{% endif %}
{% endblock content %}

blog/templates/all_categories.html
{% extends "base.html" %}
{% load markdown_extras %}

{% block title %}Все категории{% endblock title %}

{% block content %}
<h1>Категории</h1>
{% if user.is_authenticated %}
<div class="toolbar">
    <a class="button" href="{% url 'blog:new_category' %}"><i class="fa fa-plus fa-lg" aria-hidden="true"></i></a>
</div>
{% endif %}
{% if object_list.count > 0 %}
    {% for category in object_list %}
    <div>
        {% if category.parent is None %}
        <div class="blog-post-card">
            <h2><a href="{% url 'blog:category' category.pk %}">{{ category.caption }}</a></h2>
            <p class="preview">{{ category.description | markdown | safe }}</p>
            {% if category.childs.count > 0 %}
            <p><b>Подкатегории: </b>
                {% for subcategory in category.childs.all %}
                <a class="category button" href="{% url 'blog:category' subcategory.pk %}">{{subcategory.caption}}</a> 
                {% endfor %}
            </p>
            {% endif %}
            {% if user.is_authenticated %}
            <p class="category-bar">
                <a href="{% url 'blog:update_category' category.pk %}" class="button small"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                <a href="{% url 'blog:delete_category' category.pk %}" class="button small"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
            </p>
            {% endif %}
        </div>
        {% endif %}
    </div>
    {% endfor %}
{% else %}
<p>В даном разделе нет категорий</p>
{% endif %}
{% endblock content %}

blog/templates/article.html
{% extends "base.html" %}
{% load markdown_extras %}

{% block content %}
<h1>{{ article.caption }}</h1>
<div class="preview">{{ article.preview | markdown | safe }}</div>
<div class="article-bar">
    Дата публикации: {{article.public_dt|date:"l d F Y"}} г.
    &#124;
    Категория: <a href="{% url 'blog:category' article.category.pk %}">{{article.category.caption}}</a>
    {% if user.is_authenticated %}
    &#124;
    <a href="{% url 'blog:update_article' article.pk %}" class="button small"><i class="fa fa-pencil" aria-hidden="true"></i></a>
    <a href="" class="button small"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
    {% endif %}
</div>
<article class="text">
    {{ article.text | markdown | safe }}
</article>
</div>
{% endblock content %}

blog/templates/article_update.html
{% extends "base.html" %}

{% block content %}
<h1>Изменение статьи</h1>
<form method="post" action="{% url 'blog:new_article' %}">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock content %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Base Page{% endblock title %} | Cauf Blog</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/Cousine-font.css' %}" />
    <link rel="stylesheet" href="{% static 'css/RobotoCondensed-font.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Montserrat-font.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
    <link rel="stylesheet" href="{% static 'css/codestyle.css' %}" />
    <script defer type="text/javascript" src="{% static 'js/jquery_mini_351.js' %}"></script>
    <script defer type="text/javascript" src="{% static 'js/blog.js' %}"></script>
</head>

<body>
    <header>
        <div class="conteiner">
            <h1>Cauf Blog</h1>
            <div id="userdata">
            {% if user.is_authenticated %}
                <p>{{user.username}}</p>
                <a href="{% url 'logout' %}">Выйти</a>
            {% else %}
            <a href="{% url 'login' %}">Войти</a>
            {% endif %}
            </div>
        </div>
    </header>

    <main>
        {% block main %}
        <div id="content">
            {% block content %}
            <article>
                <h1>Проверка вывода текста</h1>
                <p>
                    Не вызывает сомнений, что консультация с широким активом обеспечивает широкому кругу специалистов поэтапного и последовательного развития общества. Для современного мира рамки и место обучения кадров требует от нас анализа укрепления демократической системы.
                    Разнообразный и богатый опыт рамки и место обучения кадров обеспечивает широкому кругу специалистов направлений прогрессивного развития. Равным образом реализация намеченных плановых заданий обеспечивает актуальность модели развития.
                    Значимость этих проблем настолько очевидна, что реализация намеченных плановых заданий позволяет оценить значение представляет собой интересный эксперимент позиции, занимаемых участниками в отношении поставленных задач. Равным образом
                    начало повседневной работы по формированию позиции играет важную роль в формировании прогресса профессионального общества. Следует отметить, что начало повседневной работы по формированию позиции требует определения и уточнения модели
                    развития. Следует отметить, что начало повседневной работы по формированию позиции в значительной степени обуславливает создание модели развития. С другой стороны повышение уровня гражданского сознания напрямую зависит от форм воздействия.
                    Разнообразный и богатый опыт социально-экономическое развитие обеспечивает широкому кругу специалистов экономической целесообразности принимаемых изменений.
                </p>
            </article>
            {% endblock content %}
        </div>
        <nav>
            <ul>
                <li>
                    <a class="nav-item" href="{% url 'blog:all_articles' %}">Статьи</a>
                </li>
                <li>
                    <a class="nav-item" href="">Теги</a>
                </li>
                <li>
                    <a class="nav-item" href="{% url 'blog:all_categories' %}">Категории</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a class="nav-item" href="">Изображения</a>
                </li>
                {% endif %} 
                <li>
                    <a class="nav-item" href="">Об авторе</a>
                </li>
            </ul>
        </nav>
        {% endblock main %}
    </main>

    <footer>
        <p><b>&#169; by cauf, 2021 г.</b></p>
    </footer>
</body>

</html>

blog/templates/category.html
{% extends "base.html" %}
{% load markdown_extras %}

{% block content %}
<h1>Категория &#171;{{ category.caption }}&#187;</h1>
{% if not category.articles %}
<p>Здесь пока ничего нет. :(</p>
{% else %}
{% for article in category.articles.all %}
<h2>{{article.caption}}</h2>
<div class="preview">{{ article.preview | markdown | safe }}</div>
<div class="article-bar">
    Дата публикации: {{article.public_dt|date:"l d F Y"}} г.
    {% if user.is_authenticated %}
    &#124;
    <a href="{% url 'blog:update_article' article.pk %}" class="button small"><i class="fa fa-pencil" aria-hidden="true"></i></a>
    <a href="" class="button small"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
    {% endif %}
</div>
{% endfor %}
{% endif %}

{% endblock content %}

blog/templates/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Удаление категории</h1>
<form method="post" action="{% url 'blog:delete_category' %}">{% csrf_token %}
    <p>Вы уверены, что хотите удалить категорию "{{object.caption}}"?</p>
    <button type="submit">Удалить</button>
</form>
{% endblock content %}

blog/templates/category_update.html
{% extends "base.html" %}

{% block content %}
<h1>Изменение категории</h1>
<form method="post" action="{% url 'blog:new_category' %}">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}

{% block content %}
{% if error %}
    <div class="error">{{error}}</div>
{% endif %}
<form action="" method="post">{% csrf_token %}
    <p><label for="username">Имя пользователя</label></p>
    <p><input id="username" name="username" type="text"></p>
    <p><label for="password">Пароль</label></p>
    <p><input id="password" name="password" type="password"></p>
    <button type="submit">Войти</button>
</form>
{% endblock content %}